config/routes.rb
Ginger2::Application.routes.draw do
  root to: 'main#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact/show', as: :contact

  resources :musicians, :only => [:show] do
    resources :gigs, :only => [:index]
    resources :pieces, :only => [:index]
    resources :musician_endorsements, :only => [:index]
    resources :musician_video_links, :only => [:index]
    resources :musician_images, :only => [:index]
    resources :musical_ensembles, :only => [:index]
    resources :genres, :only => [:index]
    resources :composers, :only => [:index]
  end
  resources :genres, :only => [:show]
  resources :composers, :only => [:show]
  resources :pieces, :only => [:show]
  resources :mentors, :only => [:show]
  resources :gigs, :only => [:show]
  resources :musical_ensemble_gigs, :only => [:show]
  resources :musical_ensemble_video_links, :only => [:show]
  resources :musician_endorsements, :only => [:show]
  resources :musician_video_links, :only => [:show]
  resources :musician_recording_files, :only => [:show]
  resources :musical_ensembles, :only => [:show] do
    resources :musical_ensemble_gigs, :only => [:index]
    resources :musical_ensemble_video_links, :only => [:index]
    resources :musical_ensemble_images, :only => [:index]
  end
  resources :sopranos, :only => [:show]
  resources :flutists, :only => [:show]
  resources :web_developers, :only => [:show]
  resources :web_developer_jobs
  resources :web_developer_trainings
  resources :web_developer_endorsements
  resources :web_developer_projects
  resources :web_developer_videos
  resources :inquiries, :only => [:new, :create]
  resources :endorsements, :only => [:new, :create]

end

app/models/web_developer_job.rb
class WebDeveloperJob < ActiveRecord::Base
  attr_accessible :description, :company, :duration, :location, :skills_used, :short_description, :importance, :url
  belongs_to :web_developer
end

app/controllers/web_developer_jobs_controller.rb
class WebDeveloperJobsController < ApplicationController
  def index
    @web_developer = WebDeveloper.singleton
    @jobs = @web_developer.sorted_jobs
    add_necessary_breadcrumbs
  end

  def show
    @job = WebDeveloperJob.find(params[:id])
    add_necessary_breadcrumbs
    add_breadcrumb "Job", web_developer_job_path(@job)
  end

  def add_necessary_breadcrumbs
    add_breadcrumb "Education", web_developer_trainings_path
    add_breadcrumb "Projects", web_developer_projects_path
    add_breadcrumb "Endorsements", web_developer_endorsements_path
    add_breadcrumb "Videos", web_developer_videos_path
    add_breadcrumb "Jobs", web_developer_jobs_path
  end
end

app/views/web_developer_jobs/_jobs_form.html.erb
<%= form_for @web_developer do |f| %>
  <div class="table-responsive">
    <table class="table table-striped b-t text-sm">
      <tbody>
        <% @jobs.each do |j| %>
          <tr>
            <td><%= link_to j.company, j %></td>
            <td><%= link_to j.short_description + "...", j %></td>
            <td><%= j.skills_used %></td>
            <td><%= j.duration %></td>
            <td><%= j.location %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/web_developer_jobs/index.html.erb
<h2>Work Experience</h2>
<%= render "web_developer_jobs/jobs_form" %>
<%= link_to 'Back', web_developer_path(WebDeveloper.singleton) %>

app/views/web_developer_jobs/show.html.erb
<p>
  <b>Company:</b>
  <%= @job.company %>
</p>

<p>
  <b>Timeframe:</b>
  <%= @job.duration %>
</p>

<p>
  <b>Location:</b>
  <%= @job.location %>
</p>

<p>
  <b>Skills Used:</b>
  <%= @job.skills_used %>
</p>

<p>
  <b>Description:</b>
  <%= create_pretty_text(@job.description) %>
</p>

<p>
  <b>Url:</b>
  <%= link_to @job.url, @job.url, target: "_blank" %>
</p>

<%= link_to 'Back', :back %>