config/routes.rb
Ginger2::Application.routes.draw do
  root to: 'main#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'contact/show', as: :contact

  resources :musicians, :only => [:show] do
    resources :gigs, :only => [:index]
    resources :pieces, :only => [:index]
    resources :musician_endorsements, :only => [:index]
    resources :musician_video_links, :only => [:index]
    resources :musician_images, :only => [:index]
    resources :musical_ensembles, :only => [:index]
    resources :genres, :only => [:index]
    resources :composers, :only => [:index]
  end
  resources :genres, :only => [:show]
  resources :composers, :only => [:show]
  resources :pieces, :only => [:show]
  resources :mentors, :only => [:show]
  resources :gigs, :only => [:show]
  resources :musical_ensemble_gigs, :only => [:show]
  resources :musical_ensemble_video_links, :only => [:show]
  resources :musician_endorsements, :only => [:show]
  resources :musician_video_links, :only => [:show]
  resources :musician_recording_files, :only => [:show]
  resources :musical_ensembles, :only => [:show] do
    resources :musical_ensemble_gigs, :only => [:index]
    resources :musical_ensemble_video_links, :only => [:index]
    resources :musical_ensemble_images, :only => [:index]
  end
  resources :sopranos, :only => [:show]
  resources :flutists, :only => [:show]
  resources :web_developers, :only => [:show]
  resources :web_developer_jobs
  resources :web_developer_trainings
  resources :web_developer_endorsements
  resources :web_developer_projects
  resources :web_developer_videos
  resources :inquiries, :only => [:new, :create]
  resources :endorsements, :only => [:new, :create]

end

app/models/musical_ensemble.rb
class MusicalEnsemble < ActiveRecord::Base
  attr_accessible :description, :name, :importance, :musical_ensemble_video_links_attributes,
                                 :musical_ensemble_recording_files_attributes,
                                 :musical_ensemble_links_attributes,
                                 :musical_ensemble_images_attributes,
                                 :musical_ensemble_gigs_attributes
  belongs_to :musician
  has_many :musical_ensemble_video_links
  has_many :musical_ensemble_links
  has_many :musical_ensemble_images
  has_many :musical_ensemble_gigs


  accepts_nested_attributes_for :musical_ensemble_video_links,
                                 :musical_ensemble_links,
                                 :musical_ensemble_images,
                                 :musical_ensemble_gigs,
                                 allow_destroy: true

  def main_image
    proc = Proc.new {self.musical_ensemble_images.first}
    self.musical_ensemble_images.detect(proc) do |e|
      e.main?
    end
  end

  def upcoming_gigs
    future_gigs = musical_ensemble_gigs.select do |e|
      e.performance_date >= Time.zone.now.to_date
    end
    future_gigs.sort! {|a,b| a.performance_date <=> b.performance_date}
  end

  def past_gigs
    old_gigs = musical_ensemble_gigs.select do |e|
      e.performance_date < Time.zone.now.to_date
    end
    old_gigs.sort! {|a,b| b.performance_date <=> a.performance_date}
  end

  def ordered_gigs
    musical_ensemble_gigs.sort {|a,b| a.performance_date <=> b.performance_date}
  end

  def ordered_video_links
    musical_ensemble_video_links.sort {|a,b| a.importance <=> b.importance}
  end

  def ordered_musical_ensemble_links
    musical_ensemble_links.sort {|a,b| a.importance <=> b.importance}
  end

  def most_important_musical_ensemble_link
    ordered_musical_ensemble_links.first
  end

  def main_link_url
    link = ordered_musical_ensemble_links.first
    link.nil? ? "http://www.gingergriffis.com/" : link.url
  end

  def abbreviated_description
    description.truncate(75, :omission => "...")
  end
end

app/controllers/musical_ensembles_controller.rb
class MusicalEnsemblesController < ApplicationController
  def show
    @ensemble = MusicalEnsemble.find(params[:id])
    @musician = @ensemble.musician
    @gigs = @ensemble.upcoming_gigs
    @video_links = @ensemble.ordered_video_links.take(2)
  end

  def index
    @musician = Musician.find(params[:musician_id])
    add_other_breadcrumbs
    @ensembles = @musician.ordered_by_name_musical_ensembles
  end

  def add_other_breadcrumbs
    add_breadcrumb "Samples", musician_musician_video_links_path(@musician)
    add_breadcrumb "Repertoire", musician_pieces_path(@musician)
    add_breadcrumb "Testimonials", musician_musician_endorsements_path(@musician)
    add_breadcrumb "Photo Gallery", musician_musician_images_path(@musician)
    add_breadcrumb "Gigs", musician_gigs_path(@musician)
    add_breadcrumb "Ensembles", musician_musical_ensembles_path(@musician)
  end
end

app/views/musical_ensembles/index.html.erb
<h1 class="text-center">Ensembles</h1>
<div class="table-responsive">
  <table class="table table-striped b-t text-sm">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Description</th>
        <th>Url</th>
      </tr>
    </thead>
    <tbody>
      <% @ensembles.each do |e| %>
        <tr>
          <td><%= if e.main_image then (link_to (image_tag e.main_image.image_url(:tiny).to_s), e) end %></td>
          <td><%= link_to e.name, e %></td>
          <td><%= e.abbreviated_description %></td>
          <% if e.most_important_musical_ensemble_link %>
            <td><%= link_to e.most_important_musical_ensemble_link.link_for_display, e.most_important_musical_ensemble_link.url, target: "_blank" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Back', @musician %>

app/views/musical_ensembles/show.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://cdn.embed.ly/jquery.embedly-3.1.1.min.js"></script>
<script type="text/javascript">
  $('document').ready(function(){
    $('#video_url').embedly({
      query: { maxwidth: 350, wmode: 'transparent' },
      method: 'after',
      key: '454314ac5d2c4cfa990b5444d71874ef'
    });
  });
</script>
<div class="row">
  <div class="span7">
    <div class="float-left">
      <%= link_to (image_tag @ensemble.main_image.image_url(:medium), class: "img-circle"), musical_ensemble_musical_ensemble_images_path(@ensemble) %>
      <small><div class="text-center"><%= link_to "Photo Gallery", musical_ensemble_musical_ensemble_images_path(@ensemble) %></div></small>
    </div>
    <h1><%= link_to @ensemble.name, @ensemble.main_link_url, target: "_blank" %></h1>
    <p><%= create_pretty_text(@ensemble.description) %></p>
    <p>
      <%= link_to "Inquiry?", new_inquiry_path %>
      <% @ensemble.ordered_musical_ensemble_links.each do |e| %>
        <b>|</b>&nbsp
        <%= link_to e.link_for_display, e.url, target: "_blank" %>
      <% end %>
    </p>
    <div class="boxed box-border">
      <h3><%= link_to "Upcoming Events...", musical_ensemble_musical_ensemble_gigs_path(@ensemble) %></h3>
      <%= render "gigs/gigs_form" %>
    </div>
  </div>
  <div class="span5">
    <% if @ensemble.musical_ensemble_video_links.present? %>
      <h3><%= link_to "Samples...", musical_ensemble_musical_ensemble_video_links_path(@ensemble) %></h3>
      <div id="video_url">
        <% @video_links.each do |video| %>
          <div class="col-md-8 boxed box-border">
            <b><%= link_to video.title, video %></b></br>
            <%= link_to video.url, video.url %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div><br/>
<%= link_to 'Back', :back %>